[supabase]
SUPABASE_URL = "https://vimswywxzejgyvxjzuvf.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpbXN3eXd4emVqZ3l2eGp6dXZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTk5NDYsImV4cCI6MjA2MTQzNTk0Nn0.bqcMzJaUet9yPsUEuXe6cqvKjzOBOBvQzBG6eXFl0VU"